// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvew8PLM4PQDqr91nvV5e8C3_03GclP34',
    appId: '1:725054572172:web:17db2d9a2a825562b79da9',
    messagingSenderId: '725054572172',
    projectId: 'cash-4a21f',
    authDomain: 'cash-4a21f.firebaseapp.com',
    storageBucket: 'cash-4a21f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJYPuUpVQirBs4n72aoA0O3w4OKU8HtW0',
    appId: '1:725054572172:android:a2abfac10546c736b79da9',
    messagingSenderId: '725054572172',
    projectId: 'cash-4a21f',
    storageBucket: 'cash-4a21f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHqvoYvH-UB1qhPvEqAm84NwX253tUx_0',
    appId: '1:725054572172:ios:a1f936b0e7c620c6b79da9',
    messagingSenderId: '725054572172',
    projectId: 'cash-4a21f',
    storageBucket: 'cash-4a21f.firebasestorage.app',
    iosBundleId: 'com.example.bizManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHqvoYvH-UB1qhPvEqAm84NwX253tUx_0',
    appId: '1:725054572172:ios:a1f936b0e7c620c6b79da9',
    messagingSenderId: '725054572172',
    projectId: 'cash-4a21f',
    storageBucket: 'cash-4a21f.firebasestorage.app',
    iosBundleId: 'com.example.bizManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvew8PLM4PQDqr91nvV5e8C3_03GclP34',
    appId: '1:725054572172:web:639a19e1895c2935b79da9',
    messagingSenderId: '725054572172',
    projectId: 'cash-4a21f',
    authDomain: 'cash-4a21f.firebaseapp.com',
    storageBucket: 'cash-4a21f.firebasestorage.app',
  );
}
